emulator {
  tcp {
    port = 8888
  }
    components {
      rgrip {
        enabled = true

        name = "RGRIP"

        range {
          min = 0
          max = 55
          unit = "degree"
        }
      }
    }
}